### ISSUE TITLE
Fix build.xml

### ISSUE THREAD

**Issue by shadeebarzin** [UCSB-CS56-Projects/cs56-games-fish-animation#22]
Ant clean does not remove the .class files in the build directory, ant compile gives a warning when run. Fix the build.xml file so it works properly.

**Comment by shadeebarzin** [comment]
fixed ant clean, ant compile, and removed ant runEnv (from when the game was a screensaver)

**Comment by jrcryan** [comment]
~50 points

**Comment by asyung** [comment]
F16 OK (50 pts)

**Comment by xavierholt** [comment]
As of F17 these all seem to be problems:
 - `ant clean` doesn't clean up class files.
 - `ant compile` gives an "unchecked" warning.
 - `ant RunEnv` still exists (and fails).

50 XP
